"""Regenerate INDEX.md from the current on-disk blueprints.

Run from the topology/ directory:

    cd topology && python3 ai/blueprints/_generate_index.py

The generated catalog is authoritative -- do NOT hand-edit INDEX.md,
re-run this instead.
"""

from __future__ import annotations

import os
import sys
from collections import Counter
from pathlib import Path


def main() -> int:
    here = Path(__file__).resolve().parent
    topo_root = here.parent.parent  # .../topology
    sys.path.insert(0, str(topo_root))
    # Importing here so running from anywhere resolves ai.blueprints.
    from ai.blueprints import list_blueprints, reload_blueprints  # noqa: WPS433

    reload_blueprints()
    entries = list_blueprints(limit=500)

    lines = [
        "# AI Protocol Topology Blueprint Library",
        "",
        "Auto-generated catalog of the canonical protocol-topology blueprints the AI",
        "assistant consults before emitting `create_topology`. Each entry uses the",
        "per-protocol color coding, AS / area grouping shapes, and text-box annotations",
        "documented in `topology/ai/knowledge.md`.",
        "",
        "## Workflow",
        "",
        "1. Assistant calls `list_blueprints({protocol, scale, tags, query})` to",
        "   discover which blueprints match the user ask.",
        "2. Assistant calls `load_blueprint({name})` to fetch the full JSON.",
        "3. Assistant ADAPTS device counts / names / IPs to the user's specific",
        "   scenario, then calls `create_topology` with the adapted objects.",
        "",
        "Do NOT edit this file by hand -- regenerate via",
        "`python3 ai/blueprints/_generate_index.py` from the `topology/` directory.",
        "",
        "Per-user overrides live at `~/.topology_users/<user>/ai_blueprints/*.json`",
        "and take precedence on name collision.",
        "",
        "## Catalog",
        "",
        "| Blueprint | Protocol | Scale | Devices | Links | Summary |",
        "|---|---|---|---|---|---|",
    ]
    for e in entries:
        lines.append(
            f"| `{e['name']}` | `{e['protocol']}` | {e['scale']} | "
            f"{e['device_count']} | {e['link_count']} | {e['summary']} |"
        )

    lines.append("")
    lines.append("## Tag cloud")
    lines.append("")
    tag_counter: Counter = Counter()
    for e in entries:
        for t in e.get("tags") or []:
            tag_counter[t] += 1
    for tag, count in tag_counter.most_common():
        lines.append(f"- `{tag}` ({count})")

    lines.append("")
    lines.append(f"_{len(entries)} blueprints._")
    lines.append("")

    out_path = here / "INDEX.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} with {len(entries)} blueprints")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
