#!/usr/bin/env python3
'''
Author: Bogdan Istoc

Description: This script is used to cleanup the folder structure of the autogenerated RSTs.
The configuration of how the new folder hierarchy should look like can be found inside `rst_prep_config.json`
There is no need to run this independently since this script runs automatically before the actual conversion to `.docx` (see `conversion.py`).
To cleanup the folder structure without creating the `.docx`, run the following line:
$ python3 rst_prep/main.py
'''

import os, shutil, json
from typing import List, Dict
from rst_prep.operation_dispatcher import OperationDispatcher
from rst_prep.global_knobs import GlobalKnobs
from rst_prep.operations import AbstractOperation
from rst_prep.operations import RenameRstsBasedOnCmdNamesOperation
from rst_prep import consts


CONFIG_FILE = "./rst_prep_config.json"


class RstPrep:
    def __init__(self, config_file: str) -> None:
        self.config_file: str = config_file
        self.operations: List[AbstractOperation] = []


    def prep_out_dir(self) -> int:
        in_dir = GlobalKnobs.get_in_dir()
        out_dir = GlobalKnobs.get_out_dir()
        # no need to copy the entire dir structure if the output location is also the input
        if in_dir != out_dir:
            if os.path.exists(out_dir):
                shutil.rmtree(out_dir)
            os.makedirs(out_dir)
            dirs_to_be_moved = list(os.walk(in_dir))[0][1]
            for directory in dirs_to_be_moved:
                if not directory.startswith("."):
                    shutil.copytree(os.path.join(in_dir, directory), os.path.join(out_dir, directory))
        return consts.SUCCESS


    def load_config(self) -> int:
        ret = consts.FAILURE

        config: List[Dict]
        with open(self.config_file, "r") as file:
            config = json.load(file)

        GlobalKnobs.load_from_config(config)

        errors = []
        for el in config:
            try:
                if consts.GLOBAL_KNOBS_KEY not in el:
                    operation = el.get(consts.OPERATION_KEY, None)
                    if operation is None:
                        raise Exception(f"Missing {consts.OPERATION_KEY} key for: {el}")
                    self.operations.append(OperationDispatcher.dispatch(operation, el))
            except Exception as e:
                errors.append(e)

        if any(errors):
            for e in errors:
                print(f"ERROR: {e}")
            ret = consts.FAILURE
        else:
            ret = consts.SUCCESS
        return ret


    def apply_config(self) -> int:
        self.prep_out_dir()
        for op in self.operations:
            op.run()

        if GlobalKnobs.get_rename_rsts_based_on_cmd_name():
            RenameRstsBasedOnCmdNamesOperation({consts.TARGET_KEY: os.path.abspath(GlobalKnobs.get_out_dir())}, validate_params=False).run()

        return consts.SUCCESS


def run() -> int:
    rstPrep = RstPrep(config_file=CONFIG_FILE)
    ret = rstPrep.load_config()
    if consts.SUCCESS == ret:
        ret = rstPrep.apply_config()
    return ret


if '__main__' == __name__:
    run()
