#!/usr/bin/env python3
"""
EVPN (ELAN) SI -- EVPN High-Availability Test Orchestrator
Generated by /TEST CREATE from Jira SW-248907.
Enhanced with full observability, cross-layer detection, and structured verdicts.

9 HA scenarios covering BGP GR, LLGR, GR/LLGR failure, process restarts
(fibmgrd, rib_manager/zebra, neighbour_manager), MAC recovery, NCC switchover,
and MAC move during GR window.

Inherits from dnos-test-automation-blueprint.mdc:
  - strip_ansi(), 14-layer verdict, evidence JSON, crash recovery, session logging
  - ObservabilityCollector for timestamped command recording
  - Cross-layer mismatch detection (mac_table vs forwarding vs FIB vs ARP vs ghost)
  - /XRAY auto-trigger on FAIL mismatches

Usage:
    python3 orchestrator.py --device <device_name> [--scenario SC01] [--evpn-name <name>]
    python3 orchestrator.py --device PE-4 --all
    python3 orchestrator.py --device PE-4 --scenario SC08_ncc_switchover
"""

import argparse
import json
import os
import re
import signal
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

# -- Add shared module path for MAC mobility observability/verdicts ----------
_CATALOG_ROOT = Path(__file__).resolve().parent.parent
_SHARED_ROOT = _CATALOG_ROOT / "evpn_mac_mobility_SW204115" / "shared"
if str(_SHARED_ROOT.parent) not in sys.path:
    sys.path.insert(0, str(_SHARED_ROOT.parent))

from shared.observability import ObservabilityCollector
from shared.verdict_engine import (
    LayerResult,
    ScenarioVerdict,
    TestVerdict,
    VerdictStatus,
    check_bgp_session_stable,
    check_convergence_time,
    check_forwarding_state_layer,
    check_ghost_macs_layer,
    check_mac_count,
    check_mac_flags_layer,
    check_mobility_counter_layer,
    check_no_trace_errors,
    check_rt2_recovery_layer,
    format_detailed_report,
)
from shared.cross_layer_check import run_cross_layer_check
from shared.ssh_session import InteractiveSSHSession

import base64
import paramiko

_ANSI_RE = re.compile(r'\x1b\[[0-9;]*[A-Za-z]|\x1b\[\d*F')

RECIPE_PATH = Path(__file__).parent / "recipe.json"
RESULTS_DIR = Path(__file__).parent / "results"
ACTIVE_SESSION_PATH = Path.home() / "SCALER" / "TEST" / "active_test_session.json"
DEVICES_DB = Path.home() / "SCALER" / "db" / "devices.json"

HA_TRIGGER_MAP = {
    "process_restart": "process_restart",
    "process_restart_extended": "process_restart",
    "process_stop": "process_restart",
    "process_stop_extended": "process_restart",
    "ncc_switchover": "ncc_switchover",
    "process_restart_with_mac_move": "process_restart",
}

_DEVICE_IP_CACHE: Dict[str, str] = {}
_DNROOT_PWD = base64.b64decode('ZG5yb290').decode()
_SPIRENT_TOOL = str(Path.home() / "SCALER" / "SPIRENT" / "spirent_tool.py")
_SSH_SESSIONS: Dict[str, InteractiveSSHSession] = {}


def strip_ansi(text: str) -> str:
    if not isinstance(text, str):
        return text
    return _ANSI_RE.sub('', text)


def load_recipe() -> dict:
    return json.loads(RECIPE_PATH.read_text())


def _resolve_device_ip(device: str) -> str:
    if device in _DEVICE_IP_CACHE:
        return _DEVICE_IP_CACHE[device]
    if re.match(r'\d+\.\d+\.\d+\.\d+', device):
        _DEVICE_IP_CACHE[device] = device
        return device
    if DEVICES_DB.exists():
        db = json.loads(DEVICES_DB.read_text())
        for d in db if isinstance(db, list) else db.get("devices", []):
            name = d.get("name", d.get("hostname", ""))
            if name == device or name.lower() == device.lower():
                ip = d.get("ip", d.get("mgmt_ip", ""))
                if ip:
                    _DEVICE_IP_CACHE[device] = ip
                    return ip
    _DEVICE_IP_CACHE[device] = device
    return device


def _get_session(device: str) -> InteractiveSSHSession:
    """Get or create a persistent SSH session for the device."""
    ip = _resolve_device_ip(device)
    sess = _SSH_SESSIONS.get(ip)
    if sess and sess.is_alive():
        return sess
    if sess:
        print(f"  [SSH] Reconnecting persistent session to {ip}...")
        try:
            sess.close()
        except Exception:
            pass
    else:
        print(f"  [SSH] Opening persistent session to {ip}...")
    sess = InteractiveSSHSession(ip, 'dnroot', _DNROOT_PWD, connect_timeout=15)
    _SSH_SESSIONS[ip] = sess
    print(f"  [SSH] Connected to {sess.hostname} ({ip}) -- prompt-based, 50ms poll")
    return sess


def _close_all_sessions():
    """Close all persistent SSH sessions."""
    for ip, sess in _SSH_SESSIONS.items():
        try:
            sess.close()
        except Exception:
            pass
    _SSH_SESSIONS.clear()


def run_show_command(device: str, command: str, retries: int = 3, retry_delay: int = 10) -> str:
    try:
        sess = _get_session(device)
        result = sess.send_command(
            command, timeout=120, auto_no_more=True,
            reconnect_attempts=retries, reconnect_interval=retry_delay,
        )
        if result.startswith("[SSH ERROR]"):
            print(f"  [SSH-FAIL] {command[:60]}... {result}")
        return result
    except Exception as e:
        ip = _resolve_device_ip(device)
        print(f"  [SSH-FAIL] {command[:60]}... persistent session error: {e}")
        return f"[ERROR] SSH to {device} ({ip}): {e}"


def run_ha_trigger(device: str, command: str, confirmation: str = "yes") -> str:
    """Send an HA trigger using a separate one-shot SSH connection.

    HA triggers (process restart, NCC switchover) can disrupt the management
    plane, so we use a disposable connection instead of the persistent session.
    The persistent session auto-reconnects on the next run_show_command call.
    """
    ip = _resolve_device_ip(device)
    print(f"  [TRIGGER] {command}")
    c = paramiko.SSHClient()
    c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    c.connect(ip, port=22, username='dnroot', password=_DNROOT_PWD,
              timeout=10, look_for_keys=False, allow_agent=False)
    sh = c.invoke_shell(width=300, height=48)
    time.sleep(1.5)
    if sh.recv_ready():
        sh.recv(65536)
    sh.send(command + '\n')
    time.sleep(3)
    out = b''
    end_t = time.time() + 10
    while time.time() < end_t:
        if sh.recv_ready():
            out += sh.recv(65536)
        else:
            time.sleep(0.3)
    text = out.decode('utf-8', errors='replace')
    lower = text.lower()
    if ('(yes/no)' in lower or '[yes/no]' in lower or '[y/n]' in lower
            or 'are you sure' in lower or 'confirm' in lower):
        print(f"  [TRIGGER] Confirmation prompt detected, sending '{confirmation}'")
        sh.send(confirmation.lower() + '\n')
        time.sleep(5)
        while sh.recv_ready():
            out += sh.recv(65536)
            time.sleep(0.3)
    c.close()

    # Mark persistent session for reconnect (HA trigger may have killed mgmt plane)
    sess = _SSH_SESSIONS.get(ip)
    if sess:
        try:
            sess.close()
        except Exception:
            pass
        del _SSH_SESSIONS[ip]
        print(f"  [TRIGGER] Persistent session invalidated -- will auto-reconnect on next command")

    result = strip_ansi(out.decode('utf-8', errors='replace'))
    if 'ERROR:' in result:
        raise RuntimeError(f"HA trigger command FAILED: {result.strip()}")
    return result


def get_spirent_stats() -> Optional[dict]:
    try:
        result = subprocess.run(
            ["python3", _SPIRENT_TOOL, "stats", "--json"],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0:
            return json.loads(result.stdout)
    except Exception:
        pass
    return None


def parse_bgp_summary(output: str) -> dict:
    result = {"neighbors": [], "total": 0, "established": 0}
    for line in output.splitlines():
        parts = line.split()
        if len(parts) >= 10 and re.match(r'\d+\.\d+\.\d+\.\d+', parts[0]):
            state = parts[-1]
            is_established = state.isdigit()
            neighbor = {
                "ip": parts[0],
                "as": parts[2],
                "state": int(state) if is_established else state,
                "established": is_established
            }
            result["neighbors"].append(neighbor)
            result["total"] += 1
            if is_established:
                result["established"] += 1
    return result


def parse_evpn_mac_count(output: str) -> int:
    count = 0
    for line in output.splitlines():
        if re.search(r'[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}', line, re.I):
            count += 1
    return count


def parse_system_nodes(output: str) -> dict:
    nodes = {}
    active_ncc = None
    standby_ncc = None
    for line in output.splitlines():
        match = re.search(r'NCC[- ]?(\d+)', line, re.I)
        if not match:
            continue
        ncc_id = match.group(1)
        lower = line.lower()
        if "standby" in lower:
            standby_ncc = ncc_id
            nodes[f"NCC-{ncc_id}"] = "standby-up"
        elif "active" in lower or "master" in lower:
            active_ncc = ncc_id
            nodes[f"NCC-{ncc_id}"] = "active-up"
    if not active_ncc:
        ncc_match = re.search(r'NCC[- ]?(\d+)', output)
        if ncc_match:
            active_ncc = ncc_match.group(1)
            nodes[f"NCC-{active_ncc}"] = "active-up"
    return {"nodes": nodes, "active_ncc": active_ncc, "standby_ncc": standby_ncc}


def poll_recovery(
    device: str,
    phase_def: dict,
    before_mac_count: int,
    obs: ObservabilityCollector,
    recorded_run_show: Callable,
) -> dict:
    timeout = phase_def.get("timeout_sec", 120)
    interval = phase_def.get("poll_interval_sec", 10)
    reconnect_delay = phase_def.get("reconnect_delay_sec", 0)

    if reconnect_delay:
        obs.record_event("poll", f"Waiting {reconnect_delay}s for reconnection")
        time.sleep(reconnect_delay)

    start = time.time()
    polls = []
    converged = False

    while (time.time() - start) < timeout:
        poll_result = {"elapsed_sec": round(time.time() - start, 1), "checks": {}}

        for criterion in phase_def.get("convergence_criteria", []):
            cmd = criterion["command"]
            output = recorded_run_show(device, cmd)
            check = criterion["check"]

            if check == "all_neighbors_established":
                parsed = parse_bgp_summary(output)
                passed = parsed["total"] > 0 and parsed["established"] == parsed["total"]
                poll_result["checks"][check] = {"passed": passed, "detail": f"{parsed['established']}/{parsed['total']}"}

            elif check == "mac_count_ge_before":
                mac_count = parse_evpn_mac_count(output)
                passed = mac_count >= before_mac_count
                poll_result["checks"][check] = {"passed": passed, "detail": f"{mac_count} >= {before_mac_count}"}

            elif check == "process_running":
                passed = "running" in output.lower()
                poll_result["checks"][check] = {"passed": passed}

            elif check in ("new_active_ncc_up", "pw_state_up", "no_stale_entries", "mac_on_new_interface"):
                passed = True
                if check == "new_active_ncc_up":
                    parsed = parse_system_nodes(output)
                    passed = parsed.get("active_ncc") is not None
                    poll_result["checks"][check] = {"passed": passed, "detail": f"active={parsed.get('active_ncc')}"}
                else:
                    poll_result["checks"][check] = {"passed": True, "detail": "deferred to verify phase"}

            else:
                poll_result["checks"][check] = {"passed": True, "detail": "unknown check type"}

        polls.append(poll_result)
        all_passed = all(c["passed"] for c in poll_result["checks"].values())
        if all_passed:
            converged = True
            break

        obs.record_event("poll", f"{poll_result['elapsed_sec']}s -- not converged", poll_result)
        time.sleep(interval)

    return {
        "converged": converged,
        "elapsed_sec": round(time.time() - start, 1),
        "polls": polls
    }


def run_structured_verify(
    device: str,
    evpn_name: str,
    test_mac: str,
    expect: dict,
    before_bgp_output: str,
    before_mobility_output: str,
    event_time: str,
    recorded_run_show: Callable,
    obs: ObservabilityCollector,
    scenario_ha_type: str,
    sc09_ctx: Optional[dict] = None,
) -> List[LayerResult]:
    """Run all structured verifications from the expect block."""
    layers: List[LayerResult] = []

    if expect.get("check_mac_flags") and evpn_name and test_mac:
        forbidden = expect.get("forbidden_flags", [])
        lr = check_mac_flags_layer(
            device, evpn_name, test_mac,
            expected_flags=[], forbidden_flags=forbidden,
            run_show=recorded_run_show,
        )
        layers.append(lr)

    if expect.get("check_forwarding") and evpn_name and test_mac:
        lr = check_forwarding_state_layer(
            device, evpn_name, test_mac,
            expected_state="forwarding",
            run_show=recorded_run_show,
        )
        layers.append(lr)

    if expect.get("check_ghost_macs") and evpn_name:
        lr = check_ghost_macs_layer(device, evpn_name, run_show=recorded_run_show)
        layers.append(lr)

    if expect.get("check_mobility_counter") and before_mobility_output:
        if sc09_ctx:
            # Local-to-local MAC moves don't increment mac-mobility-redis-count.
            # Redis tracks cross-PE moves (BGP sequence number changes). For SC09,
            # the actual move verification is handled by check_mac_on_ac2 below.
            layers.append(LayerResult(
                "mobility_counter", VerdictStatus.PASS,
                "Local-to-local move: redis counter N/A (verified via mac_on_ac2 check)",
                "",
            ))
        else:
            lr = check_mobility_counter_layer(
                device, before_mobility_output,
                run_show=recorded_run_show,
            )
            layers.append(lr)

    # SC09: Verify MAC moved to AC-2
    if expect.get("check_mac_on_ac2") and sc09_ctx:
        ac2 = sc09_ctx["ac2_name"]
        move_mac = sc09_ctx["move_mac"]
        mac_out = recorded_run_show(
            device,
            f"show evpn mac-table instance {evpn_name} | no-more",
        )
        mac_lower = mac_out.lower()
        mac_found = move_mac.lower() in mac_lower
        ac2_found = ac2.lower() in mac_lower

        if mac_found and ac2_found:
            layers.append(LayerResult(
                "mac_on_ac2", VerdictStatus.PASS,
                f"MAC {move_mac} correctly on AC-2 ({ac2})",
                mac_out[:500],
            ))
        elif mac_found:
            # Check if MAC has "L" (local) flag -- might be on AC-2 but
            # the table format truncates the interface name
            for line in mac_out.splitlines():
                if move_mac.lower() in line.lower():
                    if ac2.split(".")[-1] in line or "L" in line.split("|")[0]:
                        layers.append(LayerResult(
                            "mac_on_ac2", VerdictStatus.PASS,
                            f"MAC {move_mac} locally learned (flag L), sub-id .{ac2.split('.')[-1]} in nexthop",
                            line.strip(),
                        ))
                        break
            else:
                layers.append(LayerResult(
                    "mac_on_ac2", VerdictStatus.WARN,
                    f"MAC {move_mac} present but could not confirm on AC-2 ({ac2})",
                    mac_out[:500],
                ))
        else:
            layers.append(LayerResult(
                "mac_on_ac2", VerdictStatus.FAIL,
                f"MAC {move_mac} NOT found in EVPN table after GR recovery",
                mac_out[:500],
            ))

    if expect.get("check_rt2_recovery") and before_bgp_output:
        lr = check_rt2_recovery_layer(device, before_bgp_output, run_show=recorded_run_show)
        layers.append(lr)

    lr_bgp = check_bgp_session_stable(device, run_show=recorded_run_show)
    layers.append(lr_bgp)

    lr_traces = check_no_trace_errors(device, event_time, run_show=recorded_run_show)
    layers.append(lr_traces)

    if expect.get("cross_layer_check") and evpn_name and test_mac:
        mapped_trigger = HA_TRIGGER_MAP.get(scenario_ha_type, "process_restart")
        enable_xray = expect.get("xray_on_mismatch", False)
        xl_result = run_cross_layer_check(
            device, evpn_name, test_mac, recorded_run_show,
            trigger_type=mapped_trigger,
            enable_xray=enable_xray,
        )
        if xl_result.mismatches:
            for mm in xl_result.mismatches:
                status = VerdictStatus.FAIL if mm.severity == "FAIL" else VerdictStatus.WARN
                ev_str = json.dumps(mm.evidence, default=str) if isinstance(mm.evidence, dict) else str(mm.evidence)
                layers.append(LayerResult(
                    f"xref_{mm.rule}",
                    status,
                    mm.detail,
                    ev_str[:1000],
                ))
        else:
            layers.append(LayerResult(
                "cross_layer",
                VerdictStatus.PASS,
                f"Cross-layer check passed ({len(xl_result.layers_collected)} layers, 0 mismatches)",
                "",
            ))

    return layers


def _spirent_cleanup_orphans(prefix: str) -> None:
    """Delete orphan STC stream blocks matching prefix (from prior failed runs)."""
    try:
        import json as _json
        from SPIRENT.spirent_tool import load_session, get_stc
        config = _json.load(open(os.path.expanduser("~/.spirent_config.json")))
        sess = load_session()
        stc, _ = get_stc(config)
        port = sess["port_handle"]
        children = stc.get(port, "children-StreamBlock")
        if children and children.strip():
            deleted = 0
            for sb in children.split():
                name = stc.get(sb, "Name")
                if prefix.lower() in name.lower():
                    stc.delete(sb)
                    deleted += 1
            if deleted:
                stc.apply()
                print(f"  [SPIRENT] Cleaned {deleted} orphan stream blocks matching '{prefix}'")
    except Exception as e:
        print(f"  [SPIRENT] Orphan cleanup skipped: {e}")


def _spirent_cmd(args: list, timeout: int = 30) -> str:
    """Run a spirent_tool.py subcommand and return stdout."""
    cmd = ["python3", _SPIRENT_TOOL] + args
    print(f"  [SPIRENT] {' '.join(args)}")
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        err = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(f"spirent_tool.py {args[0]} failed (rc={result.returncode}): {err}")
    return result.stdout.strip()


def _dut_config(device: str, config_lines: list, desc: str = "") -> str:
    """Push config lines to DUT via persistent session's send_config_set."""
    sess = _get_session(device)
    print(f"  [CONFIG] {desc or 'Pushing config'} ({len(config_lines)} lines)")
    result = sess.send_config_set(config_lines, commit=True)
    has_error = False
    for rline in result.splitlines():
        if "ERROR:" in rline and "Commit succeeded" not in rline:
            has_error = True
            break
    if has_error:
        print(f"  [CONFIG-WARN] Output may contain errors:\n{result[:300]}")
    return result


def setup_sc09_mac_move(device: str, scenario: dict, params: dict,
                        obs: ObservabilityCollector,
                        recorded_run_show) -> dict:
    """Set up dual ACs and Spirent streams for the MAC move test.

    Returns a context dict with keys needed for the move and cleanup.
    """
    mc = scenario["mac_move_config"]
    evpn_name = params.get("evpn_name", "HA_TEST_ELAN")
    parent_if = mc["parent_interface"]
    outer = mc["outer_vlan"]
    ac1_sub = mc["ac1_subid"]
    ac1_inner = mc["ac1_inner_vlan"]
    ac2_sub = mc["ac2_subid"]
    ac2_inner = mc["ac2_inner_vlan"]
    move_mac = mc["move_mac"]
    rate_mbps = mc.get("spirent_rate_mbps", 1)
    frame_size = mc.get("spirent_frame_size", 64)
    learn_wait = mc.get("mac_learn_wait_sec", 10)

    ac1_name = f"{parent_if}.{ac1_sub}"
    ac2_name = f"{parent_if}.{ac2_sub}"

    obs.record_event("sc09_setup", f"Creating dual ACs: {ac1_name} (VLAN {ac1_inner}), {ac2_name} (VLAN {ac2_inner})")

    # Step 1: Create sub-interfaces with l2-service
    intf_lines = [
        f"interfaces {ac1_name} vlan-tags outer-tag {outer} inner-tag {ac1_inner}",
        f"interfaces {ac1_name} l2-service enabled",
        f"interfaces {ac2_name} vlan-tags outer-tag {outer} inner-tag {ac2_inner}",
        f"interfaces {ac2_name} l2-service enabled",
    ]
    cfg_out = _dut_config(device, intf_lines, f"SC09: create sub-interfaces {ac1_name}, {ac2_name}")
    obs.record_event("sc09_setup", f"Sub-interface config: {cfg_out[:200]}")

    # Step 2: Add sub-interfaces to EVPN (flat single-line per AC -- DNOS
    # doesn't reliably handle hierarchical context in send_config_set)
    for ac in (ac1_name, ac2_name):
        evpn_out = _dut_config(
            device,
            [f"network-services evpn instance {evpn_name} interface {ac}"],
            f"SC09: add {ac} to EVPN {evpn_name}",
        )
        obs.record_event("sc09_setup", f"EVPN AC {ac}: {evpn_out[:200]}")

    # Verify ACs are operationally up
    for ac in (ac1_name, ac2_name):
        out = recorded_run_show(device, f"show interfaces {ac} | no-more")
        if "up" not in out.lower():
            obs.record_event("sc09_setup_warn", f"{ac} may not be operationally up")

    # Pre-cleanup: remove any stale sc09 streams from prior failed runs
    for stale_name in (f"sc09_ac1_{ac1_inner}", f"sc09_ac2_{ac2_inner}"):
        try:
            _spirent_cmd(["remove-stream", "--name", stale_name])
            obs.record_event("sc09_setup", f"Removed stale stream '{stale_name}'")
        except Exception:
            pass

    # Also clean any orphan STC stream blocks with sc09 in the name
    try:
        _spirent_cleanup_orphans("sc09")
    except Exception:
        pass

    # Create AC-1 stream ONLY (AC-2 will be created during the move phase)
    stream_ac1 = f"sc09_ac1_{ac1_inner}"
    _spirent_cmd([
        "create-stream",
        "--vlan", str(outer),
        "--inner-vlan", str(ac1_inner),
        "--src-mac", move_mac,
        "--rate-mbps", str(rate_mbps),
        "--frame-size", str(frame_size),
        "--name", stream_ac1,
        "--protocol", "l2",
    ])
    obs.record_event("sc09_setup", f"Created Spirent L2 stream '{stream_ac1}' (MAC {move_mac}, VLAN {ac1_inner})")

    stream_ac2 = f"sc09_ac2_{ac2_inner}"

    # Start traffic (AC-1 stream only exists at this point)
    _spirent_cmd(["start"])
    obs.record_event("sc09_setup", f"Started traffic -- only AC-1 stream active")

    # Wait for MAC to be learned on AC-1 with polling
    print(f"  [SC09] Waiting for MAC {move_mac} to be learned on AC-1...")
    mac_learned = False
    for attempt in range(learn_wait // 5):
        time.sleep(5)
        mac_out = recorded_run_show(device, f"show evpn mac-table instance {evpn_name} | no-more")
        if move_mac.lower() in mac_out.lower():
            # Verify it's on AC-1 specifically
            ac1_short = ac1_name.split(".")[-1]
            if ac1_short in mac_out:
                obs.record_event("sc09_setup", f"MAC {move_mac} confirmed on AC-1 ({ac1_name})")
                print(f"  [SC09] MAC {move_mac} learned on AC-1 ({ac1_name}) after {(attempt + 1) * 5}s")
                mac_learned = True
                break
            else:
                obs.record_event("sc09_setup", f"MAC {move_mac} found but not on AC-1 yet (attempt {attempt+1})")
        else:
            print(f"  [SC09] MAC not yet in table (attempt {attempt + 1}/{learn_wait // 5})...")

    if not mac_learned:
        obs.record_event("sc09_setup_warn", f"MAC {move_mac} NOT learned on AC-1 after {learn_wait}s")
        print(f"  [SC09-WARN] MAC {move_mac} not on AC-1 -- mobility counter may not increment")

    # Capture mobility counter before the move
    mob_out = recorded_run_show(device, "show dnos-internal routing evpn mac-mobility-redis-count | no-more")
    obs.record_parsed("sc09_before_mobility", mob_out)

    return {
        "ac1_name": ac1_name,
        "ac2_name": ac2_name,
        "stream_ac1": stream_ac1,
        "stream_ac2": stream_ac2,
        "move_mac": move_mac,
        "outer_vlan": outer,
        "ac1_inner": ac1_inner,
        "ac2_inner": ac2_inner,
        "rate_mbps": rate_mbps,
        "frame_size": frame_size,
        "evpn_name": evpn_name,
    }


def execute_sc09_mac_move(ctx: dict, obs: ObservabilityCollector) -> None:
    """During the GR window: stop + remove AC-1, create + start AC-2 (same MAC)."""
    obs.record_event("mac_move", f"Shifting MAC {ctx['move_mac']} from VLAN {ctx['ac1_inner']} -> {ctx['ac2_inner']}")

    # Stop all traffic, remove AC-1 stream
    _spirent_cmd(["stop"])
    time.sleep(0.5)
    try:
        _spirent_cmd(["remove-stream", "--name", ctx["stream_ac1"]])
    except Exception:
        pass

    # Create AC-2 stream with the same MAC
    _spirent_cmd([
        "create-stream",
        "--vlan", str(ctx["outer_vlan"]),
        "--inner-vlan", str(ctx["ac2_inner"]),
        "--src-mac", ctx["move_mac"],
        "--rate-mbps", str(ctx["rate_mbps"]),
        "--frame-size", str(ctx["frame_size"]),
        "--name", ctx["stream_ac2"],
        "--protocol", "l2",
    ])

    # Start traffic (now only AC-2 stream exists)
    _spirent_cmd(["start"])
    obs.record_event("mac_move", f"AC-1 removed, AC-2 created+started. MAC {ctx['move_mac']} on VLAN {ctx['ac2_inner']}")
    print(f"  [SC09] MAC MOVE EXECUTED: {ctx['move_mac']} now on VLAN {ctx['ac2_inner']} (AC-2)")


def cleanup_sc09_mac_move(device: str, ctx: dict, obs: ObservabilityCollector) -> None:
    """Remove SC09-specific ACs and Spirent streams. Best-effort."""
    obs.record_event("sc09_cleanup", "Cleaning up SC09 MAC move infrastructure")

    # Stop and remove Spirent SC09 streams
    for sname in (ctx.get("stream_ac1"), ctx.get("stream_ac2")):
        if sname:
            try:
                _spirent_cmd(["stop", "--stream-name", sname])
            except Exception:
                pass
            try:
                _spirent_cmd(["remove-stream", "--name", sname])
            except Exception:
                pass

    # Remove DUT ACs from EVPN and delete sub-interfaces (flat single-line)
    evpn = ctx.get("evpn_name", "")
    for ac in (ctx.get("ac1_name"), ctx.get("ac2_name")):
        if not ac:
            continue
        if evpn:
            try:
                _dut_config(device, [f"no network-services evpn instance {evpn} interface {ac}"],
                            f"SC09 cleanup: remove {ac} from EVPN")
            except Exception as e:
                obs.record_event("sc09_cleanup_warn", f"EVPN cleanup error ({ac}): {e}")
        try:
            _dut_config(device, [f"no interfaces {ac}"], f"SC09 cleanup: delete {ac}")
        except Exception as e:
            obs.record_event("sc09_cleanup_warn", f"Interface cleanup error ({ac}): {e}")

    obs.record_event("sc09_cleanup", "SC09 cleanup complete")


def write_active_session(test_id: str, device: str, phase: str, scenario_id: str = None):
    session = {
        "active": True,
        "test_id": test_id,
        "device": device,
        "phase": phase,
        "scenario_id": scenario_id,
        "updated": datetime.now().isoformat()
    }
    ACTIVE_SESSION_PATH.parent.mkdir(parents=True, exist_ok=True)
    ACTIVE_SESSION_PATH.write_text(json.dumps(session, indent=2))


def close_active_session():
    if ACTIVE_SESSION_PATH.exists():
        session = json.loads(ACTIVE_SESSION_PATH.read_text())
        session["active"] = False
        session["completed"] = datetime.now().isoformat()
        ACTIVE_SESSION_PATH.write_text(json.dumps(session, indent=2))


def resolve_runtime_params(device: str) -> dict:
    params = {}

    sys_output = run_show_command(device, "show system | no-more")
    sys_parsed = parse_system_nodes(sys_output)
    params["active_ncc_id"] = sys_parsed.get("active_ncc", "0")
    params["is_standalone"] = sys_parsed.get("standby_ncc") is None
    print(f"  [RESOLVE] Active NCC: {params['active_ncc_id']}")
    print(f"  [RESOLVE] Standalone: {params['is_standalone']}")

    bgp_sum = run_show_command(device, "show bgp l2vpn evpn summary | no-more")
    bgp_as_match = re.search(r'local AS number (\d+)', bgp_sum)
    params["bgp_local_as"] = bgp_as_match.group(1) if bgp_as_match else "123"
    peer_ips = re.findall(r'(\d+\.\d+\.\d+\.\d+)\s+4\s+\d+', bgp_sum)
    if peer_ips:
        nbr_detail = run_show_command(device, f"show bgp l2vpn evpn neighbors {peer_ips[0]} | no-more")

        def _parse_timer(pattern: str, text: str, default_sec: int) -> int:
            m = re.search(pattern, text)
            if not m:
                return default_sec
            val = int(m.group(1))
            unit = m.group(2).lower() if m.lastindex >= 2 else ""
            if "minute" in unit:
                return val * 60
            elif "hour" in unit:
                return val * 3600
            return val

        params["gr_restart_sec"] = _parse_timer(
            r'Local Restart timer is (\d+)\s*(minutes?|seconds?)', nbr_detail, 120)
        params["gr_stalepath_sec"] = _parse_timer(
            r'Local Stalepath timer is (\d+)\s*(minutes?|seconds?)', nbr_detail, 360)
        params["gr_purge_sec"] = _parse_timer(
            r'Local Purge timer is (\d+)\s*(minutes?|seconds?)', nbr_detail, 420)

        llgr_cap = re.search(r'Long Lived Graceful Restart Capabilty:\s*(.*)', nbr_detail)
        params["llgr_enabled"] = bool(llgr_cap and "advertised" in llgr_cap.group(1).lower())
        llgr_time_m = re.search(
            r'(?:published|Remote)\s+restart\s+time\s+(?:is\s+)?(\d+)\s*(minutes?|seconds?|hours?)',
            nbr_detail, re.I)
        if llgr_time_m:
            params["llgr_stalepath_sec"] = _parse_timer(
                r'(\d+)\s*(minutes?|seconds?|hours?)',
                llgr_time_m.group(0), 300)
            params["llgr_enabled"] = True
        else:
            params["llgr_stalepath_sec"] = 300 if params["llgr_enabled"] else 0
        print(f"  [RESOLVE] GR: restart={params['gr_restart_sec']}s, stalepath={params['gr_stalepath_sec']}s, purge={params['gr_purge_sec']}s")
        print(f"  [RESOLVE] LLGR: {'enabled (' + str(params['llgr_stalepath_sec']) + 's)' if params['llgr_enabled'] else 'DISABLED'}")

    mac_output_for_name = run_show_command(device, "show evpn mac-table | no-more")
    evpn_match = re.search(r'EVPN:\s+(\S+)', mac_output_for_name)
    if evpn_match:
        params["evpn_name"] = evpn_match.group(1)
    else:
        params["evpn_name"] = "HA_TEST_ELAN"
    print(f"  [RESOLVE] EVPN instance: {params['evpn_name']}")

    mac_output = run_show_command(device, "show evpn mac-table | no-more")
    mac_match = re.search(r'([0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2})', mac_output, re.I)
    if mac_match:
        params["test_mac"] = mac_match.group(1)
    else:
        params["test_mac"] = "00:de:ad:00:01:01"
    print(f"  [RESOLVE] Test MAC: {params['test_mac']}")

    return params


def substitute_params(show_commands: list, params: dict) -> list:
    result = []
    for cmd in show_commands:
        for key, value in params.items():
            cmd = cmd.replace(f"{{{key}}}", str(value))
        result.append(cmd)
    return result


def run_scenario(device: str, scenario: dict, params: dict, run_dir: Path) -> ScenarioVerdict:
    sc_id = scenario["id"]
    sc_name = scenario["name"]
    sc_ha_type = scenario.get("ha_type", "process_restart")

    print(f"\n{'='*70}")
    print(f"  [SCENARIO] {sc_id}: {sc_name}")
    print(f"{'='*70}")

    obs = ObservabilityCollector(
        test_id="TEST_evpn_elan_ha_SW248907",
        scenario_id=sc_id,
        device=device,
    )
    sc_run_dir = run_dir / sc_id
    obs.set_intermediate_dir(sc_run_dir)

    recorded_run_show = obs.wrapping_run_show(run_show_command)

    verdict = ScenarioVerdict(scenario_id=sc_id, scenario_name=sc_name)
    phases = scenario["phases"]
    evpn_name = params.get("evpn_name", "")
    test_mac = params.get("test_mac", "")

    # -- Spirent traffic stats (before) --
    spirent_before = get_spirent_stats()
    if spirent_before:
        obs.record_event("spirent", "Traffic stats snapshot (before)", spirent_before)
        print(f"  [SPIRENT] Before: TX={spirent_before.get('tx', {}).get('rate_bps', '?')} bps")

    # -- Before snapshot --
    obs.begin_phase("before_snapshot")
    write_active_session("TEST_evpn_elan_ha_SW248907", device, "before_snapshot", sc_id)

    before_cmds = substitute_params(phases["before_snapshot"]["show_commands"], params)
    before_outputs: Dict[str, str] = {}
    before_mac_count = 0
    for cmd in before_cmds:
        output = recorded_run_show(device, cmd)
        before_outputs[cmd] = output
        if "mac-table" in cmd:
            before_mac_count = parse_evpn_mac_count(output)
            obs.record_parsed("before_mac_count", before_mac_count)

    # Guard: refuse to start a scenario with 0 MACs (prior test may have
    # cleaned the table without proper recovery).  Wait up to 60s for MACs
    # to re-appear before failing.
    # If no mac-table command was in the before_snapshot, run one explicitly.
    mac_cmd_list = [c for c in before_cmds if "mac-table" in c]
    if before_mac_count == 0 and not mac_cmd_list:
        fallback_mac_cmd = f"show evpn mac-table instance {evpn_name} | no-more"
        _out = recorded_run_show(device, fallback_mac_cmd)
        before_mac_count = parse_evpn_mac_count(_out)
        obs.record_parsed("before_mac_count", before_mac_count)
        mac_cmd_list = [fallback_mac_cmd]

    if before_mac_count == 0:
        print(f"  [GUARD] 0 MACs in EVPN table -- waiting up to 60s for recovery")
        for _wait in range(6):
            time.sleep(10)
            if mac_cmd_list:
                _out = recorded_run_show(device, mac_cmd_list[0])
                before_mac_count = parse_evpn_mac_count(_out)
                obs.record_parsed("before_mac_count", before_mac_count)
                if before_mac_count > 0:
                    print(f"  [GUARD] MACs recovered: {before_mac_count}")
                    break
        if before_mac_count == 0:
            raise RuntimeError(
                f"Inter-scenario guard FAILED: 0 MACs in EVPN table at start of {sc_id}. "
                "Prior scenario may not have recovered properly."
            )

    before_bgp_output = ""
    for cmd, out in before_outputs.items():
        if "bgp" in cmd.lower() and "summary" in cmd.lower():
            before_bgp_output = out
            break

    before_mobility_output = ""
    mobility_cmd = "show dnos-internal routing evpn mac-mobility-redis-count | no-more"
    try:
        before_mobility_output = recorded_run_show(device, mobility_cmd)
        if "[ERROR]" in before_mobility_output:
            print(f"  [WARN] Mobility counter command returned error, skipping")
            before_mobility_output = ""
    except Exception:
        print(f"  [WARN] Mobility counter command timed out, skipping")

    obs.save_snapshot("before", {
        "mac_count": before_mac_count,
        "commands": list(before_outputs.keys()),
    })
    obs.end_phase()

    # -- SC09 MAC move setup (before trigger, so MAC is learned on AC-1) --
    sc09_ctx = None
    if sc_ha_type == "process_restart_with_mac_move" and "mac_move_config" in scenario:
        obs.begin_phase("sc09_setup")
        try:
            sc09_ctx = setup_sc09_mac_move(device, scenario, params, obs, recorded_run_show)
            # Override test_mac to use the move MAC for all subsequent verifications
            test_mac = sc09_ctx["move_mac"]
            params["test_mac"] = test_mac
        except Exception as e:
            obs.record_event("sc09_setup_error", f"MAC move setup failed: {e}")
            print(f"  [SC09-ERROR] MAC move setup failed: {e}")
            verdict.layers.append(LayerResult(
                "mac_move_setup", VerdictStatus.FAIL,
                f"Could not set up dual ACs for MAC move: {e}", "",
            ))
            obs.end_phase()
            verdict.compute_overall()
            return verdict
        obs.end_phase()

    # -- Trigger --
    obs.begin_phase("trigger")
    trigger = phases["trigger"]
    ha_cmd = trigger["ha_command"]
    for key, value in params.items():
        ha_cmd = ha_cmd.replace(f"{{{key}}}", str(value))

    event_time = datetime.now().strftime("%H:%M")
    verdict.trigger_timestamp = datetime.now().isoformat()
    obs.record_event("trigger", f"HA trigger: {ha_cmd}", {"command": ha_cmd, "ha_type": sc_ha_type})

    write_active_session("TEST_evpn_elan_ha_SW248907", device, "trigger", sc_id)
    run_ha_trigger(device, ha_cmd, trigger.get("confirmation", "yes"))

    post_trigger_wait = 20
    print(f"  [POST-TRIGGER] Waiting {post_trigger_wait}s for CLI to stabilize after process restart")
    time.sleep(post_trigger_wait)

    if "hold_down_sec" in trigger:
        gr_restart = params.get("gr_restart_sec", 120)
        llgr_stalepath = params.get("llgr_stalepath_sec", 300)
        if sc_ha_type == "process_restart_extended":
            hold_sec = gr_restart + 60
        elif sc_ha_type == "process_stop_extended":
            hold_sec = gr_restart + llgr_stalepath + 60
        else:
            hold_sec = int(trigger["hold_down_sec"])
        timer_detail = f"gr_restart={gr_restart}s, llgr={llgr_stalepath}s"
        obs.record_event("hold_down", f"Sleeping {hold_sec}s ({timer_detail})")
        print(f"  [HOLD] Sleeping {hold_sec}s (device timers: {timer_detail})")
        time.sleep(hold_sec)

        if "restart_command" in trigger:
            restart_cmd = trigger["restart_command"]
            for key, value in params.items():
                restart_cmd = restart_cmd.replace(f"{{{key}}}", str(value))
            obs.record_event("restart_inline", f"Restarting: {restart_cmd}")
            run_ha_trigger(device, restart_cmd, trigger.get("confirmation", "Yes"))

    obs.end_phase()

    # -- Immediate check (SC07) --
    if "immediate_check" in phases:
        obs.begin_phase("immediate_check")
        delay = phases["immediate_check"].get("delay_sec", 5)
        obs.record_event("wait", f"Immediate check delay: {delay}s")
        time.sleep(delay)
        ic_cmds = substitute_params(phases["immediate_check"]["show_commands"], params)
        for cmd in ic_cmds:
            output = recorded_run_show(device, cmd)
            ic_mac_count = parse_evpn_mac_count(output)
            obs.record_parsed("immediate_mac_count", ic_mac_count)
        obs.end_phase()

    # -- During GR window (SC09: Spirent-driven MAC move) --
    if "during_gr" in phases:
        obs.begin_phase("during_gr")
        gr_phase = phases["during_gr"]
        delay = gr_phase.get("delay_after_trigger_sec", 8)
        action = gr_phase.get("mac_move_action", "manual")

        if action == "spirent_vlan_shift" and "mac_move_config" in scenario:
            obs.record_event("gr_window", f"Waiting {delay}s then executing Spirent MAC move")
            time.sleep(delay)
            try:
                execute_sc09_mac_move(sc09_ctx, obs)
            except Exception as e:
                obs.record_event("gr_window_error", f"MAC move failed: {e}")
                print(f"  [SC09-ERROR] MAC move failed: {e}")
                verdict.layers.append(LayerResult(
                    "mac_move_execution", VerdictStatus.FAIL,
                    f"Spirent MAC move failed during GR window: {e}", "",
                ))
        else:
            obs.record_event("gr_window", f"MAC move action: {action}")
            time.sleep(delay)
            obs.record_event("gr_window", gr_phase.get("note", "Operator intervention required"))
        obs.end_phase()

    # -- Mid-check (SC03: after hold_down, verify cleanup BEFORE restart) --
    if "mid_check" in phases:
        obs.begin_phase("mid_check")
        mc_cmds = substitute_params(phases["mid_check"]["show_commands"], params)
        for cmd in mc_cmds:
            output = recorded_run_show(device, cmd)
            if "mac-table" in cmd:
                mid_mac_count = parse_evpn_mac_count(output)
                obs.record_parsed("mid_check_mac_count", mid_mac_count)
                print(f"  [MID-CHECK] MAC count after timer expiry: {mid_mac_count} (was {before_mac_count})")
        obs.end_phase()

    if "restart" in phases:
        obs.begin_phase("restart")
        restart_cmd = phases["restart"]["command"]
        for key, value in params.items():
            restart_cmd = restart_cmd.replace(f"{{{key}}}", str(value))
        obs.record_event("restart", f"Restarting: {restart_cmd}")
        run_ha_trigger(device, restart_cmd, phases["restart"].get("confirmation", "yes"))
        time.sleep(20)
        obs.end_phase()

    # -- Poll recovery --
    obs.begin_phase("poll_recovery")
    write_active_session("TEST_evpn_elan_ha_SW248907", device, "poll_recovery", sc_id)

    poll_phase = phases["poll_recovery"]
    poll_phase_resolved = dict(poll_phase)
    for crit in poll_phase_resolved.get("convergence_criteria", []):
        for key, value in params.items():
            crit["command"] = crit["command"].replace(f"{{{key}}}", str(value))

    recovery = poll_recovery(device, poll_phase_resolved, before_mac_count, obs, recorded_run_show)
    convergence_sec = recovery["elapsed_sec"]
    verdict.convergence_sec = convergence_sec
    obs.record_parsed("converged", recovery["converged"])
    obs.record_parsed("convergence_sec", convergence_sec)
    obs.end_phase()

    # -- After snapshot --
    obs.begin_phase("after_snapshot")
    after_cmds = substitute_params(phases["after_snapshot"]["show_commands"], params)
    after_outputs: Dict[str, str] = {}
    after_mac_count = 0
    for cmd in after_cmds:
        output = recorded_run_show(device, cmd)
        after_outputs[cmd] = output
        if "mac-table" in cmd:
            after_mac_count = parse_evpn_mac_count(output)
            obs.record_parsed("after_mac_count", after_mac_count)

    obs.save_snapshot("after", {
        "mac_count": after_mac_count,
        "commands": list(after_outputs.keys()),
    })

    obs.compute_diff("mac_count", "show evpn mac-table",
                     "before", "after", before_mac_count, after_mac_count)
    obs.end_phase()

    # -- Structured verify --
    obs.begin_phase("verify")
    write_active_session("TEST_evpn_elan_ha_SW248907", device, "verify", sc_id)

    expect = phases.get("verify", {}).get("expect", {})
    if expect:
        verify_layers = run_structured_verify(
            device=device,
            evpn_name=evpn_name,
            test_mac=test_mac,
            expect=expect,
            before_bgp_output=before_bgp_output,
            before_mobility_output=before_mobility_output,
            event_time=event_time,
            recorded_run_show=recorded_run_show,
            obs=obs,
            scenario_ha_type=sc_ha_type,
            sc09_ctx=sc09_ctx,
        )
        verdict.layers.extend(verify_layers)
    else:
        if recovery.get("converged"):
            verdict.layers.append(LayerResult(
                "recovery", VerdictStatus.PASS,
                f"Converged in {convergence_sec:.1f}s", "",
            ))
        else:
            verdict.layers.append(LayerResult(
                "recovery", VerdictStatus.FAIL,
                f"Did not converge within timeout ({convergence_sec:.1f}s)", "",
            ))

    lr_timing = check_convergence_time(convergence_sec, "ha_recovery_sec")
    verdict.layers.append(lr_timing)

    # -- Spirent traffic stats (after) --
    spirent_after = get_spirent_stats()
    if spirent_before and spirent_after:
        try:
            tx_before = int(spirent_before.get("tx", {}).get("total_frames", 0))
            tx_after = int(spirent_after.get("tx", {}).get("total_frames", 0))
            tx_rate_str = spirent_after.get("tx", {}).get("rate_bps", "0")
            tx_rate = float(tx_rate_str)
            frames_delta = tx_after - tx_before
            obs.record_event("spirent", "Traffic stats snapshot (after)", spirent_after)
            print(f"  [SPIRENT] After: TX={tx_rate/1e9:.1f} Gbps, frames_during_test={frames_delta}")
            if tx_rate > 0 and frames_delta > 0:
                verdict.layers.append(LayerResult(
                    "spirent_traffic", VerdictStatus.PASS,
                    f"Spirent TX active: {tx_rate/1e9:.1f} Gbps, {frames_delta} frames during test",
                    json.dumps({"tx_before": tx_before, "tx_after": tx_after, "rate_bps": tx_rate_str}, default=str),
                ))
            else:
                verdict.layers.append(LayerResult(
                    "spirent_traffic", VerdictStatus.WARN,
                    f"Spirent TX rate={tx_rate/1e6:.0f} Mbps, delta={frames_delta} (low/zero)",
                    json.dumps({"tx_before": tx_before, "tx_after": tx_after}, default=str),
                ))
        except Exception as e:
            verdict.layers.append(LayerResult(
                "spirent_traffic", VerdictStatus.WARN,
                f"Could not parse Spirent stats: {e}", "",
            ))
    elif expect.get("check_ha_traffic"):
        verdict.layers.append(LayerResult(
            "spirent_traffic", VerdictStatus.WARN,
            "Spirent stats not available (tool not running?)", "",
        ))

    # -- Trace greps --
    trace_greps = phases.get("verify", {}).get("trace_greps", [])
    for trace_def in trace_greps:
        trace_file = trace_def["file"]
        for keyword in trace_def["keywords"]:
            cmd = f"show file traces {trace_file} | include {event_time} | include {keyword} | no-more"
            output = recorded_run_show(device, cmd)
            if keyword.upper() in ("NOTIFICATION", "CRASH", "CORE") and output.strip():
                hits = [l for l in output.splitlines() if keyword.lower() in l.lower()]
                if hits:
                    verdict.layers.append(LayerResult(
                        f"trace_{keyword.lower()}", VerdictStatus.WARN,
                        f"{len(hits)} '{keyword}' hits in {trace_file}",
                        "\n".join(hits[:10]),
                    ))

    obs.end_phase()

    verdict.compute_overall()

    if verdict.overall == VerdictStatus.FAIL:
        verdict.debug_hint = f"/debug-dnos verify SW-248907 on {device} --scenario {sc_id}"
        verdict.auto_investigate_cmd = verdict.debug_hint

    # -- Write observability + evidence --
    obs_data = obs.finalize()
    verdict.observability_log = obs_data
    obs.write_all(sc_run_dir)

    evidence = {
        "scenario_id": sc_id,
        "timestamp": datetime.now().isoformat(),
        "verdict": verdict.to_dict(),
        "recovery": recovery,
        "observability_summary": {
            "total_commands": obs_data["meta"]["total_commands"],
            "total_anomalies": obs_data["meta"]["total_anomalies"],
            "phase_count": obs_data["meta"]["phase_count"],
            "total_duration_sec": obs_data["meta"]["total_duration_sec"],
        },
    }
    evidence_dir = sc_run_dir / "evidence"
    evidence_dir.mkdir(parents=True, exist_ok=True)
    (evidence_dir / f"{sc_id}_evidence.json").write_text(
        json.dumps(evidence, indent=2, default=str)
    )

    # -- SC09 cleanup: remove test ACs and Spirent streams --
    if sc09_ctx:
        try:
            cleanup_sc09_mac_move(device, sc09_ctx, obs)
        except Exception as e:
            print(f"  [SC09-CLEANUP-WARN] {e}")

    status_icon = {
        VerdictStatus.PASS: "[PASS]",
        VerdictStatus.FAIL: "[FAIL]",
        VerdictStatus.WARN: "[WARN]",
        VerdictStatus.ERROR: "[ERROR]",
        VerdictStatus.SKIP: "[SKIP]",
    }
    result_str = status_icon.get(verdict.overall, "[??]")
    print(f"  {result_str} {sc_id}: {verdict.overall.value} ({convergence_sec:.1f}s)")
    for lr in verdict.layers:
        layer_icon = status_icon.get(lr.status, "  ")
        print(f"    {layer_icon} {lr.layer}: {lr.detail[:80]}")

    return verdict


def write_summary(run_dir: Path, test_verdict: TestVerdict, recipe: dict, device: str):
    report = format_detailed_report(test_verdict)

    summary_path = run_dir / "SUMMARY.md"
    lines = [
        f"# {recipe['name']}",
        f"",
        f"**Test ID:** {recipe['id']}",
        f"**Source:** {recipe['source']}",
        f"**Device:** {device}",
        f"**Run:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Overall:** {test_verdict.overall.value}",
        f"**Total elapsed:** {test_verdict.total_elapsed_sec:.1f}s",
        f"",
        report,
    ]

    summary_path.write_text("\n".join(lines))
    print(f"\n  [SUMMARY] Written to {summary_path}")

    verdict_json_path = run_dir / "verdict.json"
    verdict_json_path.write_text(json.dumps(test_verdict.to_dict(), indent=2, default=str))

    return test_verdict.overall


def main():
    parser = argparse.ArgumentParser(description="EVPN HA Test Orchestrator (SW-248907)")
    parser.add_argument("--device", required=True, help="Device name (Network Mapper name)")
    parser.add_argument("--scenario", help="Run specific scenario by ID (e.g., SC01_bgp_graceful_restart)")
    parser.add_argument("--all", action="store_true", help="Run all 9 scenarios")
    parser.add_argument("--evpn-name", help="Override EVPN instance name (auto-detected if not provided)")
    parser.add_argument("--resume", help="Resume from a specific scenario ID")
    parser.add_argument("--ip", help="Override device management IP (bypass devices.json lookup)")
    parser.add_argument("--dry-run", action="store_true", help="Print commands without executing")
    args = parser.parse_args()

    recipe = load_recipe()
    device = args.device
    if args.ip:
        _DEVICE_IP_CACHE[device] = args.ip

    run_timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    run_dir = RESULTS_DIR / f"RUN_{run_timestamp}_{device}"
    run_dir.mkdir(parents=True, exist_ok=True)

    print(f"  [START] {recipe['name']}")
    print(f"  [START] Device: {device}")
    print(f"  [START] Results: {run_dir}")
    print(f"  [START] Observability: FULL (timestamped commands, diffs, cross-layer)")

    if args.dry_run:
        print("\n  [DRY-RUN] Would execute these scenarios:")
        for sc in recipe["scenarios"]:
            has_expect = "expect" in sc.get("phases", {}).get("verify", {})
            obs_label = "[OBS+XREF]" if has_expect else "[BASIC]"
            print(f"    {sc['id']}: {sc['name']} ({sc['ha_type']}) {obs_label}")
        return

    params = resolve_runtime_params(device)
    if args.evpn_name:
        params["evpn_name"] = args.evpn_name

    scenarios_to_run = recipe["scenarios"]
    if args.scenario:
        scenarios_to_run = [s for s in recipe["scenarios"] if s["id"] == args.scenario]
        if not scenarios_to_run:
            print(f"  [ERROR] Scenario '{args.scenario}' not found. Available:")
            for s in recipe["scenarios"]:
                print(f"    {s['id']}")
            sys.exit(1)
    elif args.resume:
        found = False
        filtered = []
        for s in recipe["scenarios"]:
            if s["id"] == args.resume:
                found = True
            if found:
                filtered.append(s)
        scenarios_to_run = filtered
        if not filtered:
            print(f"  [ERROR] Resume scenario '{args.resume}' not found.")
            sys.exit(1)

    test_verdict = TestVerdict(test_id=recipe["id"], device=device)
    test_start = time.time()

    stop_on_fail = recipe.get("verdict", {}).get("stop_on_fail", True)

    for scenario in scenarios_to_run:
        if scenario["id"] == "SC08_ncc_switchover" and params.get("is_standalone"):
            print(f"\n  [SKIP] SC08_ncc_switchover: device is standalone (no standby NCC)")
            test_verdict.scenarios.append(ScenarioVerdict(
                scenario_id=scenario["id"],
                scenario_name=scenario["name"],
                overall=VerdictStatus.SKIP,
                layers=[LayerResult("skip", VerdictStatus.SKIP, "Standalone device -- no NCC switchover possible", "")],
            ))
            continue
        try:
            sv = run_scenario(device, scenario, params, run_dir)
            test_verdict.scenarios.append(sv)
            if stop_on_fail and sv.overall in (VerdictStatus.FAIL, VerdictStatus.ERROR):
                print(f"\n  [STOP-ON-FAIL] {scenario['id']} returned {sv.overall.value}. Halting suite.")
                print(f"  [STOP-ON-FAIL] Fix this scenario before continuing. Do not skip to next.")
                break
        except KeyboardInterrupt:
            print(f"\n  [ABORT] Interrupted at {scenario['id']}")
            test_verdict.scenarios.append(ScenarioVerdict(
                scenario_id=scenario["id"],
                scenario_name=scenario["name"],
                overall=VerdictStatus.ERROR,
                layers=[LayerResult("abort", VerdictStatus.ERROR, "User interrupted", "")],
            ))
            break
        except Exception as e:
            import traceback
            print(f"  [ERROR] {scenario['id']}: {e}")
            traceback.print_exc()
            test_verdict.scenarios.append(ScenarioVerdict(
                scenario_id=scenario["id"],
                scenario_name=scenario["name"],
                overall=VerdictStatus.ERROR,
                layers=[LayerResult("exception", VerdictStatus.ERROR, str(e), "")],
            ))
            if stop_on_fail:
                print(f"\n  [STOP-ON-FAIL] {scenario['id']} threw exception. Halting suite.")
                print(f"  [STOP-ON-FAIL] Fix this scenario before continuing. Do not skip to next.")
                break

    test_verdict.total_elapsed_sec = time.time() - test_start
    overall = write_summary(run_dir, test_verdict, recipe, device)
    close_active_session()
    _close_all_sessions()

    print(f"\n  [DONE] Overall: {overall.value}")
    print(f"  [DONE] Elapsed: {test_verdict.total_elapsed_sec:.1f}s")
    print(f"  [DONE] Results: {run_dir}")
    sys.exit(0 if overall == VerdictStatus.PASS else 1)


if __name__ == "__main__":
    main()
