SUCCESS = 0
FAILURE = 1


# confi file attributes
GLOBAL_KNOBS_KEY = "GLOBAL_KNOBS"
RSTS_ROOT_KEY = "IN_DIR"
OUT_RST_DIR_KEY = "OUT_DIR"
RENAME_RSTS_BASED_ON_CMD_NAME_KEY = "RENAME_RSTS_BASED_ON_CMD_NAME"
FIX_MULTILINE_TABLES_KEY = "FIX_MULTILINE_TABLES"

TARGET_KEY = "target"
DEST_KEY = "dest"
FILES_KEY = "files"
OPERATION_KEY = "action"
