"""
AUTO-GENERATED by scaler/TEST/shared/recipe_to_dnos_e2e.py -- DO NOT EDIT BY HAND.
Source recipe: TEST_mac_mob_basic_SW205160 (SW-205160 / epic SW-204115)

Behavioral mcDNOS port of the lab MAC-mobility recipe. Proves the same EVPN MAC
learning outcomes (L> local AC, B> remote EVPN via RT-2) on hermetic mcDNOS
containers with software traffic, suitable for CI (dtest dnos_e2e).

Topology:
    mcdnos1 (local AC source) --ge100-0/0/0-- SA1 (DUT) --ge100-0/0/0-- mcdnos2 (remote EVPN PE)
    EVPN AC learning: mcdnos1 floods -> SA1 learns L> ; mcdnos2 advertises RT-2 -> SA1 installs B>
    LAB-ONLY (not emitted to CI): SC03_v_pw_via_rrsa2_ac: VPLS-PW Seamless-Integration depends on bgp-vpls label-block carving (see known bug SW-253359 on clusters) and a real PW peer; not faithfully reproducible on a single-container mcDNOS. Cover v> via the CDNOS SI suite (src/tests/cdnos/tests/test_bgp_evpn_seamless_integration.py) or keep lab-only via Spirent.
"""
import ipaddress
import logging
import pytest

from ..dnos_e2e_base import DnosE2EBase
from ..dnos_e2e_test_config import (
    ClusterRequirement, LinkDefinition, TestConfiguration, TestMode, TopologyRequirements,
)
from ..dnos_e2e_network_dataclasses import (
    TopologyNetworkConfig, RouterConfig, BGPRouterConfig, BGPRouterInfo,
    BGPNeighborInfo, InterfaceConfig, EVPNInstanceConfig, EVPNBGPConfig, CountersValidation,
)
from dnos_e2e_utils.actions.bgp_actions import ConfigBGPRouter, ConfigBGPNeighborsForEVPN, DisableBGPNeighbors, ConfigBGPNetwork
from dnos_e2e_utils.actions.interface_actions import ConfigIPInterface, ConfigL2ServiceInterface, ConfigVlanL2SubInterface, BaseConfigInterface, ClearInterfaceCounters
from dnos_e2e_utils.actions.evpn_actions import ConfigureEVPN, DeleteEVPN
from dnos_e2e_utils.actions.general_actions import ExecuteWithConfigCleanup, ActionsSequenceExecutor
from dnos_e2e_utils.actions.system_actions import SaveConfig, LoadOverrideConfig, DeleteFileDnosCli
from dnos_e2e_utils.actions.traffic_actions import ArpPingFloodDNOS
from dnos_e2e_utils.validations.evpn_validations import ValidateEvpnMacTable, ValidateBGPevpnRoutes
from dnos_e2e_utils.validations.interface_validations import ValidateInterfaceOperationalState, ValidateInterfaceCounters
from dnos_e2e_utils.dnos_e2e_device_definitions import MCDnosDefinition
from dnos_e2e_utils.consts import BGPStates, SetupTypes, InterfaceAdminState
from dnos_e2e_utils.dnos_e2e_routing_utils import get_interface_mac_address
from dn_common.globals import dn_services
from utils.jira_utils import JiraComponent

logger = logging.getLogger(__name__)

EVI_NAME = "mob-evpn"
BGP_AS = 100
VLAN_ID_A = 1500

SA1_TO_MC2 = ipaddress.ip_interface("3.1.1.1/24")
MC2_TO_SA1 = ipaddress.ip_interface("3.1.1.2/24")
MC1_TO_SA1 = ipaddress.ip_interface("2.1.1.2/24")
SA1_ROUTER_ID = "2.1.1.1"
RD = f"{SA1_TO_MC2.ip}:10"
RT = "10:10"
FEC = "rs-fec-528-514"

ARP_MAC = "aa:bb:cc:dd:ee:ff"
FLOOD_COUNT = 200
TX_MIN = 200
RX_MIN = 20
CTR_TIMEOUT = 90

# Pinned test MACs (deterministic, from recipe scenarios)
MAC_LOCAL = "00:de:ad:00:01:01"
MAC_REMOTE = "00:de:ad:00:02:01"


@pytest.mark.dnos_e2e_evpn_mobility
class TestMacMobilityBasicMcdnos(DnosE2EBase):
    """MAC mobility basic learning on mcDNOS (CI port of SW-205160)."""

    @classmethod
    def create_topology_requirements(cls, topology_handler):
        sa1_name = topology_handler.first_device_name(setup_type=SetupTypes.SA)
        return TopologyRequirements(
            topology_handler=topology_handler,
            devices=[MCDnosDefinition(name="mcdnos1"), MCDnosDefinition(name="mcdnos2")],
            physical_links=[
                LinkDefinition(
                    peer1_device_name=sa1_name,
                    peer1_interface_name=topology_handler.get_sa_interface1_name(),
                    peer2_device_name="mcdnos1",
                    peer2_interface_name="ge100-0/0/0",
                ),
                LinkDefinition(
                    peer1_device_name=sa1_name,
                    peer1_interface_name=topology_handler.get_sa_interface2_name(),
                    peer2_device_name="mcdnos2",
                    peer2_interface_name="ge100-0/0/0",
                ),
            ],
        )

    @pytest.fixture(scope="class", autouse=True)
    def set_topology_requirements(self, request):
        request.cls._topology_requirements = self.create_topology_requirements(self._topology_handler)

    @classmethod
    def _resolve_names_and_links(cls):
        cls.DUT = "SA1"
        cls.LOCAL = "mcdnos1"
        cls.REMOTE = "mcdnos2"
        cls.DUT_AC = cls._topology_handler.links.get_device_port(cls.DUT, cls.LOCAL)
        cls.DUT_TO_REMOTE = cls._topology_handler.links.get_device_port(cls.DUT, cls.REMOTE)
        cls.REMOTE_TO_DUT = cls._topology_handler.links.get_device_port(cls.REMOTE, cls.DUT)
        cls.LOCAL_TO_DUT = cls._topology_handler.links.get_device_port(cls.LOCAL, cls.DUT)

    @pytest.fixture(scope="class", autouse=True)
    def set_topology_network_config(self, request, set_topology_requirements):
        cls = request.cls
        cls._resolve_names_and_links()
        cls.DUT_BGP = BGPRouterInfo(local_as=BGP_AS, router_id=str(SA1_TO_MC2.ip))
        cls.REMOTE_BGP = BGPRouterInfo(local_as=BGP_AS, router_id=str(MC2_TO_SA1.ip))

        dut_ac_iface = InterfaceConfig(interface_name=cls.DUT_AC, fec=FEC, speed=100)
        dut_ctrl_iface = InterfaceConfig(
            interface_name=cls.DUT_TO_REMOTE, ipv4_address=str(SA1_TO_MC2), fec=FEC, speed=100)
        remote_ctrl_iface = InterfaceConfig(
            interface_name=cls.REMOTE_TO_DUT, ipv4_address=str(MC2_TO_SA1), fec=FEC, speed=100)
        remote_ac_iface = InterfaceConfig(
            interface_name=f"{cls.REMOTE_TO_DUT}.{VLAN_ID_A}", speed=100)
        # LOCAL (mcdnos1) source interface facing the DUT AC -- its MAC is what the DUT learns as L>
        local_src_iface = InterfaceConfig(
            interface_name=cls.LOCAL_TO_DUT, ipv4_address=str(MC1_TO_SA1), fec=FEC, speed=100)

        cls.TOPOLOGY_NETWORK_CONFIG = TopologyNetworkConfig(routers={
            cls.DUT: RouterConfig(
                router_name=cls.DUT,
                interfaces=[dut_ac_iface, dut_ctrl_iface],
                bgp_config=BGPRouterConfig(
                    router_info=cls.DUT_BGP,
                    neighbor_info=[BGPNeighborInfo(
                        neighbor_ip=str(MC2_TO_SA1.ip), source_interface=cls.DUT_TO_REMOTE,
                        remote_as=BGP_AS, address_family="l2vpn-evpn", community_type="both")],
                ),
                evpn_config=EVPNInstanceConfig(
                    evpn_name=EVI_NAME, interfaces=[dut_ac_iface.interface_name],
                    bgp_config=EVPNBGPConfig(bgp_as=BGP_AS, route_distinguisher=RD,
                                             export_route_target=RT, import_route_target=RT)),
            ),
            cls.LOCAL: RouterConfig(router_name=cls.LOCAL, interfaces=[local_src_iface]),
            cls.REMOTE: RouterConfig(
                router_name=cls.REMOTE,
                interfaces=[remote_ctrl_iface, remote_ac_iface],
                bgp_config=BGPRouterConfig(
                    router_info=cls.REMOTE_BGP,
                    neighbor_info=[BGPNeighborInfo(
                        neighbor_ip=str(SA1_TO_MC2.ip), source_interface=cls.REMOTE_TO_DUT,
                        remote_as=BGP_AS, address_family="l2vpn-evpn", community_type="both")],
                ),
                evpn_config=EVPNInstanceConfig(
                    evpn_name=EVI_NAME, interfaces=[remote_ac_iface.interface_name],
                    bgp_config=EVPNBGPConfig(bgp_as=BGP_AS, route_distinguisher=f"{MC2_TO_SA1.ip}:10",
                                             export_route_target=RT, import_route_target=RT)),
            ),
        })

    @classmethod
    def create_default_test_config(cls) -> TestConfiguration:
        return TestConfiguration(test_mode=TestMode.DNOS_MODE,
                                 cluster_requirement=ClusterRequirement.SA_ONLY)

    @pytest.fixture(scope="class", autouse=True)
    def set_default_test_config(self, request, set_topology_network_config):
        cls = request.cls
        merged = cls.create_default_test_config().merge_with(
            TestConfiguration(topology_requirements=cls._topology_requirements))
        cls.default_test_config = cls.default_test_config.merge_with(merged)

    @pytest.mark.owner(user="youruser", component=JiraComponent.ROUTING)
    @pytest.mark.testing_task(component=JiraComponent.ROUTING, epic="SW-204115",
                              testing_task="SW-205160", test_description="MAC Mobility | Basic Learning (rewritten 2026-05-01)")
    def test_mac_mobility_basic(self):
        """SC01 (L> local AC) + SC02 (B> remote EVPN) + SC04 coexistence on mcDNOS."""
        dut_h = self._topology_handler.topology[self.DUT]
        remote_h = self._topology_handler.topology[self.REMOTE]
        local_h = self._topology_handler.topology[self.LOCAL]
        re_container = dn_services.ContainerType.ROUTING_ENGINE.service

        # --- configure interfaces + BGP-EVPN + EVPN instances on DUT and REMOTE ---
        self._configure_suite(dut_h, remote_h)

        # ============ SC01: L> local AC learning + RT-2 advertised ============
        ClearInterfaceCounters(cluster_handler=dut_h, interface=self.DUT_AC).execute()
        # MAC the DUT will learn as L> = LOCAL node's source-interface MAC.
        # LIVE-VALIDATE: confirm get_interface_mac_address(cli, iface_name) signature + that
        # local_h cli resolves on mcDNOS during first `dtest dnos_e2e` run.
        local_cli = self._cli_of(local_h)
        local_mac = get_interface_mac_address(local_cli, self.LOCAL_TO_DUT)
        ArpPingFloodDNOS(
            cluster_handler=local_h, container_name=re_container,
            destination_ip=SA1_ROUTER_ID, count=FLOOD_COUNT, arp_mac=ARP_MAC,
            clear_mac_table=True, evpn_name=EVI_NAME, receiver_cluster_handler=dut_h,
            transmitter_validations=[CountersValidation(
                name=self.LOCAL_TO_DUT, counter_field="TX frames", operator=">=",
                expected_value=TX_MIN, timeout=CTR_TIMEOUT)],
            receiver_validations=[ValidateInterfaceCounters(
                cluster_handler=dut_h, counters_data=[CountersValidation(
                    name=self.DUT_AC, counter_field="RX frames", operator=">=",
                    expected_value=RX_MIN, timeout=CTR_TIMEOUT)])],
        ).execute()

        ValidateEvpnMacTable(cluster_handler=dut_h, evpn_name=EVI_NAME,
                             expected_mac=local_mac.lower(), timeout=30).execute()
        type2_local = f"type:=2,eth-tag:=0,mac-address:={local_mac.lower()}"
        ValidateBGPevpnRoutes(cluster_handler=dut_h, expected_content=[type2_local], timeout=30).execute()
        ValidateBGPevpnRoutes(cluster_handler=remote_h, expected_content=[type2_local], timeout=30).execute()
        logger.info("SC01 PASS: L> learned on DUT AC and RT-2 advertised to remote PE")

        # ============ SC02: B> remote EVPN learn (DUT receives RT-2) ============
        # Flooding the remote AC makes REMOTE learn locally and advertise RT-2; DUT installs B>.
        ArpPingFloodDNOS(
            cluster_handler=remote_h, container_name=re_container,
            destination_ip=str(SA1_TO_MC2.ip), count=FLOOD_COUNT, arp_mac=ARP_MAC,
        ).execute()
        remote_cli = self._cli_of(remote_h)
        remote_mac = get_interface_mac_address(remote_cli, self.REMOTE_TO_DUT)
        type2_remote = f"type:=2,eth-tag:=0,mac-address:={remote_mac.lower()}"
        ValidateBGPevpnRoutes(cluster_handler=dut_h, expected_content=[type2_remote], timeout=30).execute()
        ValidateEvpnMacTable(cluster_handler=dut_h, evpn_name=EVI_NAME,
                             expected_mac=remote_mac.lower(), timeout=30).execute()
        logger.info("SC02 PASS: DUT received RT-2 from remote PE (B>)")

        # ============ SC04: coexistence + stability ============
        ValidateEvpnMacTable(cluster_handler=dut_h, evpn_name=EVI_NAME,
                             expected_mac=local_mac.lower(), timeout=30).execute()
        ValidateEvpnMacTable(cluster_handler=dut_h, evpn_name=EVI_NAME,
                             expected_mac=remote_mac.lower(), timeout=30).execute()
        logger.info("SC04 PASS: L> and B> coexist on DUT; no suppression/ghost expected")

    @staticmethod
    def _cli_of(cluster_handler):
        """Resolve the active-NCC CLI for a cluster handler (mirrors reference rollback usage)."""
        return cluster_handler.clis[cluster_handler.active_ncc.node_name]

    def _configure_suite(self, dut_h, remote_h):
        """Mirror reference: config interfaces + BGP-EVPN network + EVPN instances with cleanup."""
        bgp_actions, bgp_cleanup, expected = [], [], {}
        for name, h in ((self.DUT, dut_h), (self.REMOTE, remote_h)):
            rc = self.TOPOLOGY_NETWORK_CONFIG.get_router(name)
            for iface in rc.interfaces:
                if "." in iface.interface_name and iface.interface_name.split(".")[-1].isdigit():
                    ConfigVlanL2SubInterface(cluster_handler=h, interface_config=iface,
                                             vlan_id=VLAN_ID_A).execute()
                elif getattr(iface, "ipv4_address", None):
                    ConfigIPInterface(cluster_handler=h, interface_config=iface).execute()
                else:
                    ConfigL2ServiceInterface(cluster_handler=h, interface_config=iface).execute()
            bgp_actions.append(ConfigBGPRouter(cluster_handler=h, router_info=rc.bgp_config.router_info))
            bgp_actions.append(ConfigBGPNeighborsForEVPN(
                cluster_handler=h, local_as=rc.bgp_config.router_info.local_as,
                neighbor_info=rc.bgp_config.neighbor_info))
            bgp_cleanup.append(DisableBGPNeighbors(
                cluster_handler=h, local_as=rc.bgp_config.router_info.local_as,
                neighbor_info=rc.bgp_config.neighbor_info))
            expected[h] = rc.bgp_config.neighbor_info
        ConfigBGPNetwork(bgp_config_actions=bgp_actions, expected_neighbors_info=expected,
                         expected_state=BGPStates.ESTABLISHED).execute()
        for name, h in ((self.DUT, dut_h), (self.REMOTE, remote_h)):
            ConfigureEVPN(cluster_handler=h,
                          evpn_config=self.TOPOLOGY_NETWORK_CONFIG.get_router(name).evpn_config).execute()
